= Lisk SDK examples
:toc:

This repository contains working code examples and example blockchain applications using the Lisk SDK.

== Guides: code examples

This is a collection of working code examples, which are used in the Lisk SDK documentation.

All code examples are grouped after the guide that contains them in the documentation

== Tutorials: full example blockchain applications

Each example project represents an industry use case in which we showcase the potential of the Lisk SDK and how it can transform this industry.

All industry use cases will be kept up to date with the latest Lisk SDK release.

=== link:tutorials/hello[Hello World]
A hello world application built with the Lisk SDK v6.

Implements the `HelloModule`, which is saving a custom string into the senders account.
It demonstrates the use of On-Chain and Off-Chain architecture by creating a custom module and a plugin for a blockchain client.

It is also equipped with a basic react frontend app including the most common interactions.

=== link:tutorials/nft[NFT Demo]
A blockchain application built with the Lisk SDK v5.

Allows a user to create, transfer, and purchase NFTs.
It is also equipped with a react frontend app to show the usage of transactions.

=== link:tutorials/postboard[Postboard]
A blockchain application built with the Lisk SDK v5.

Postboard is a Twitter-like application that offers the possibility to create/post and re-post opinions, follow other users' accounts, like posts, etc.

=== link:tutorials/social-recovery[Social Recovery System (SRS)]
A blockchain application built with the Lisk SDK v5.

The SRS offers the functionality to enable users to build an account recovery tool to assist in retrieving lost funds.

=== link:tutorials/lisk-name-service[Lisk Name Service (LNS)]
A blockchain application built with the Lisk SDK v5.

The LNS provides users with the ability to create a domain name service for their blockchain accounts.

=== https://github.com/LiskHQ/lisk-sdk-examples/tree/v4/archive/3.x/transport[Supply chain:Lisk Transport]
A blockchain application built with the Lisk SDK v3.

Originally, the Lisk Transport workshop was designed for the **Lisk.js 2019** event.
The project represents a flow where a carrier can sign up to pick up a packet, and deliver it to the right person in a decentralized manner.
A custom transaction helps with locking the fee for the drive and a warranty in case the package gets damaged or lost.
During the whole transport cycle, the packet is tracked, and it can fire alarms that get saved on the blockchain.

In addition, anyone can become a carrier.
For example, you can pick up a packet that has its destination on your daily commute and earn a small reward for this.

