= Lisk SDK examples
:toc:

This repository contains working code examples and example blockchain applications using the Lisk SDK.

== Guides: code examples

This is a collection of working code examples, which are used in the Lisk SDK documentation.

All code examples are grouped after the guide that contains them in the documentation

== Tutorials: full example blockchain applications

Each example project represents an industry use case in which we showcase the potential of the Lisk SDK and how it can transform this industry.

All industry use cases will be kept up to date with the latest Lisk SDK release.
Also, you'll find an `/archive` folder that contains older examples referring to previous Lisk SDK releases.
At the moment, the `/archive` folder contains examples for Lisk SDK `v2`, `v3` and `v4`.

=== link:tutorials/hello-world[Hello World]
A hello world application built with the Lisk SDK v5.

Implements the `HelloModule`, which is saving a custom string into the senders account.
It also equipped with a basic react frontend app including the most common interactions.

=== link:tutorials/nft[NFT Demo]
A blockchain application built with the Lisk SDK v5.

It demonstrates the use of On-Chain and Off-Chain architecture by creating a custom module and a plugin for Lisk application.
A few transactions are also included.
It also equipped with a react frontend app to show the usage of transactions.

=== link:tutorials/archive/4.x/transport[Supply chain: Lisk Transport]
A blockchain application built with the Lisk SDK v4.

Originally, the Lisk Transport workshop has been designed for the **Lisk.js 2019** event.
The project represents a flow where a carrier can sign up to pick up a packet and deliver it to the right person in a decentralized way.
A custom transaction helps with locking the fee for the drive and a warranty in case the package gets damaged or lost.
During the whole transport cycle, the packet is tracked and it can fire alarms that get saved on the blockchain.

In addition, anyone can become a carrier.
For example, you can pick up a packet that has its destination on your daily commute and earn a small reward for this.
