const BASE_RECOVERY_DEPOSIT = '1000000000';
const FRIEND_FACTOR_FEE = 2;
const CREATE_RECOVERY_ASSET_ID = 0;
const INITIATE_RECOVERY_ASSET_ID = 1;
const CLAIM_RECOVERY_ASSET_ID = 3;
const REMOVE_RECOVERY_ASSET_ID = 5;


module.exports = {
  BASE_RECOVERY_DEPOSIT,
  FRIEND_FACTOR_FEE,
  CREATE_RECOVERY_ASSET_ID,
  CLAIM_RECOVERY_ASSET_ID,
  INITIATE_RECOVERY_ASSET_ID,
  REMOVE_RECOVERY_ASSET_ID,
};
