export const LNS_PREFIX = 'LNS';
export const MIN_TTL_VALUE = 60 * 60; // 1 hour
export const VALID_TLDS = ['lsk'];
export const EMPTY_BUFFER = Buffer.alloc(0);
export const CNAME_RECORD_TYPE = 1;
export const TXT_RECORD_TYPE = 2;
export const VALID_RECORD_TYPES = [CNAME_RECORD_TYPE, TXT_RECORD_TYPE];
export const MAX_RECORDS = 50;
export const MIN_RECORD_LABEL_LENGTH = 3;
export const MAX_RECORD_LABEL_LENGTH = 15;
export const MIN_RECORD_VALUE_LENGTH = 3;
export const MAX_RECORD_VALUE_LENGTH = 255;
