const ED25519_PUBLIC_KEY_LENGTH = 32;
const ED25519_SIGNATURE_LENGTH = 64;
const MAX_DATA_LENGTH = 64;
const CHAIN_ID_LENGTH = 4;
const LOCAL_ID_LENGTH = 4;
const TOKEN_ID_LENGTH = CHAIN_ID_LENGTH + LOCAL_ID_LENGTH;


module.exports = { ED25519_PUBLIC_KEY_LENGTH, ED25519_SIGNATURE_LENGTH, MAX_DATA_LENGTH, TOKEN_ID_LENGTH };