= Lisk Transport scripts

These scripts let you create custom transaction objects from the command line.

This logic is implemented in the client app as well, these scripts are only for reference or can be used as an alternative approach from the command line.

Create and initialize a new packet account::
Creates public/private key pair, address and passphrase for a new account.
The sender also automatically sends some tokens over to the new created account, to make it appear in the database.
[source, bash]
----
node create_and_initialize_packet_account.js
----

Register a packet on the blockhain::
Before running the script, open `print_sendable_register_package.js` and set as `packetId` the ID you received when running `create_and_initialize_packet_account.js` .
[source, bash]
----
node print_sendable_register_packet.js | tee >(curl -X POST -H "Content-Type: application/json" -d @- localhost:4000/api/transactions)

----

Get Account data for a specific ID::
To check if the packet registration was successful, check the packet account:
[source, bash]
----
curl -X GET "http://localhost:4000/api/accounts?address=933972897873682359L" | python -m json.tool
----

Expected result:
[source,json]
----
{
    "data": [
        {
            "address": "933972897873682359L",
            "asset": {
                "carrier": null,
                "minTrust": 5,
                "postage": "500000000",
                "recipient": "10881167371402274308L",
                "security": "10000000000",
                "sender": "16313739661670634666L",
                "status": "pending"
            },
            "balance": "500001235",
            "publicKey": "",
            "secondPublicKey": ""
        }
    ],
    "links": {},
    "meta": {
        "limit": 10,
        "offset": 0
    }
}
----
