const SRS_MODULE_ID = 1000;
const SRS_CREATE_ASSET_ID = 0;
const SRS_INITIATE_ASSET_ID = 1;
const SRS_VOUCH_ASSET_ID = 2;
const SRS_CLAIM_ASSET_ID = 3;
const SRS_CLOSE_ASSET_ID = 4;
const SRS_REMOVE_ASSET_ID = 5;
const DEFAULT_FEE = BigInt('200000');
const TOKEN_MODULE_ID = 2;
const TOKEN_TRANSFER_ASSET_ID = 0;

module.exports = {
    SRS_MODULE_ID,
    SRS_CREATE_ASSET_ID,
    DEFAULT_FEE,
    TOKEN_MODULE_ID,
    TOKEN_TRANSFER_ASSET_ID,
    SRS_INITIATE_ASSET_ID,
    SRS_VOUCH_ASSET_ID,
    SRS_CLAIM_ASSET_ID,
    SRS_CLOSE_ASSET_ID,
    SRS_REMOVE_ASSET_ID,
};
